name: mail
on:
  poll:
    url: http://worldtimeapi.org/api/timezone/Europe/Berlin
    config:
    every: "*/5 * * * *"
    paths: 'actionsflow/workflows/Impfnachweise.zip'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "email"
  email:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1) download attachement and body_html file from own repo into container
      - name: download file
        env:
          TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          TOKEN_GIPHY: ${{ secrets.API_TOKEN_GIPHY }}
        run: |
          curl -H "Authorization: token ${TOKEN_GITHUB}" https://raw.githubusercontent.com/s0539722/actionsflow/main/workflows/Impfnachweise.zip -O -J -L
          curl -H "Authorization: token ${TOKEN_GITHUB}" https://raw.githubusercontent.com/s0539722/actionsflow/main/workflows/html_body.html -O -J -L
          curl "https://api.giphy.com/v1/gifs/search?api_key=${TOKEN_GIPHY}&q=%27rock%20music%27&limit=1" --output response.json -J -L
          cat response.json
          URL="$(jq 'data[0].url' response.json)"
          sed -i "s/{MEME_URL}/${URL}/g" html_body.html
      # 2) user action-send-mail to send the email
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: mail.gmx.net
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Impfnachweise - Die Gute Stube
          # Required recipients' addresses:
          to: punkvoter.com@gmail.com
          #to: tonkollektiv.status@gmail.com
          # Required sender full name (address can be skipped):
          from: Sebastian John <sebastian.john@gmx.net>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          #body: "Hallo,\n\n anbei die vier Impfnachweise der Guten Stube."
          # Optional HTML body read from file:
          html_body: file://html_body.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          #bcc: h.schechtmann@gmx.de, daniel.giest@yahoo.de, hanneskirchhof@web.de, sebastian.john@gmx.net
          # Optional recipient of the email response:
          reply_to: sebastian.john@gmx.net
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          #convert_markdown: true
          # Optional attachments:
          attachments: Impfnachweise.zip
          # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low
